[package]
name = "mta_status"
version = "0.1.0"
authors = ["toidiu <toidiu@protonmail.com>"]

[dependencies]
xml-rs = "0.6.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
html5ever = "0.18.0"
futures = "0.1.14"
futures-cpupool = "0.1"
tokio-core = "0.1.7"

[dependencies.hyper]
version = "0.11"
#branch = "master"
#git = "https://github.com/hyperium/hyper"
