[package]
name = "mta_status"
version = "0.1.0"
authors = ["toidiu <toidiu@protonmail.com>"]

[dependencies]
xml-rs = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
html5ever = "0.18"
tokio-core = "0.1"

[dependencies.futures]
version = "0.1"
default-features = false

[dependencies.hyper]
version = "0.11"
#branch = "master"
#git = "https://github.com/hyperium/hyper"

[[bin]]
name = "mta-status"
test = true
path = "src/bin/main.rs"